# Copyright 2025 Gregory Kiesel
# 
# support for Raspberry Pi 

FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ="America/New_York"
RUN apt-get update 
RUN apt-get install -y tzdata
RUN apt-get install -y \ 
    python3 \
    python3-pip
RUN pip3 install --upgrade adafruit-python-shell 

# set up user
RUN useradd -r pi
WORKDIR /home/pi




